## Cleaning exercise | <u>Customer call list</u> Database

Some context: This database is loaded fron github following a video and also making some self changes, things that I get interested in along the analysis.

This is a basic exercise when the final goal is to deliver a database suitable to call clients, the ones that allow the company to contact them.

Tha database is evaluated column by column and the some changes acrros the whole dataset.

## Conclusions

1. This Notebook is a **JupyerLab Notebook** which is differente from the previous exercise, I was using jupyter notebook, this one is an improved version
2. Did not say before but the reason my notebooks are in english is because **the learning material I usually use is in english** so this is easier.
3. As im doing this exercise **I tend to remember code used previously so thats a good learning sign.**
4. Im not only guided by videos, **Im also turning to the pandas library** website among others.
5. Is still hard though to remember the exact syntax, I dont see it as a problem cause I have all the resources available,but yes **is not 100% memory**
6. Cleaning exercices **specially feels as lots of practice is needed**, probably because you could find yourself in multiple scenarios.
7. Testing and looking at some errors **gives a little more sensibility to understand them, not to get scared** and just fix them, debugging becomes more natural
8. working with phone numers was specailly difficult cause sometimes is needed to treat them as strings. In this exercise i made variuos mistakes and had to drop the column off
9. Probably the **best lesson of this exercise was** how to run the code first and then check and then **Inplace** or explicit **df = ...**, I could not see the changes and sometimes i wanted to see the change

## 1. Import libraries_For *df* and *charts*

In [6]:
import pandas as pd
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
import seaborn.objects as so

sns.set_theme(style='darkgrid')

## 2. Read the file

In [7]:
df = pd.read_excel('/Users/alexandrasarmiento/Downloads/Customer Call List.xlsx')

In [10]:
# Explor the information | First glance

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

## 3. Identify the columns

In [12]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

## 4. Identify the variables types

In [11]:
df.dtypes

CustomerID            int64
First_Name           object
Last_Name            object
Phone_Number         object
Address              object
Paying Customer      object
Do_Not_Contact       object
Not_Useful_Column      bool
dtype: object

# 5. Start Cleaning

## 5.1 Drop off duplicates _ ONLY if needed

In [15]:
# df.drop_duplicates() eliminate those duplicates
# df = df.drop_duplicates() saves those changes !!

df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

## 5.2 Drop off NOT neccesary columns

In [25]:
# df.drop (columns = 'Not_Useful_Column') to remove unwanted columns_ I already saved it
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

## 5.3 Using 'strip'to remove spaces or unwanted characters

In [43]:
# Cleaning the 'last_Name' column
# String takes off spaces , right and left

df['Last_Name']= df['Last_Name'].str.lstrip ('...')
df['Last_Name']= df['Last_Name'].str.lstrip('/')
df['Last_Name']=df['Last_Name'].str.rstrip('_')
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Y,N,Baggins,123 Shire Lane,Shire,
1,1002,Abed,Nadir,93 West Main Street,N,Y,Nadir,93 West Main Street,,
2,1003,Walter,White,298 Drugs Driveway,N,,/White,298 Drugs Driveway,,
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,123 Dragons Road,Y,N,Snow,123 Dragons Road,,
5,1006,Ron,Swanson,768 City Parkway,Y,Y,Swanson,768 City Parkway,,
6,1007,Jeff,Winger,1209 South Street,N,N,Winger,1209 South Street,,
7,1008,Sherlock,Holmes,98 Clue Drive,N,N,Holmes,98 Clue Drive,,
8,1009,Gandalf,,123 Middle Earth,Y,,,123 Middle Earth,,
9,1010,Peter,Parker,"25th Main Street, New York",Y,N,Parker,25th Main Street,New York,
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Y,N,Gamgee,612 Shire Lane,Shire,
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,,Potter,2394 Hogwarts Avenue,,
12,1013,Don,Draper,2039 Main Street,Y,N,Draper,2039 Main Street,,
13,1014,Leslie,Knope,343 City Parkway,Y,N,Knope,343 City Parkway,,
14,1015,Toby,Flenderson,214 HR Avenue,N,N,Flenderson_,214 HR Avenue,,
15,1016,Ron,Weasley,2395 Hogwarts Avenue,N,N,Weasley,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Y,N,Scott,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,3498 Super Lane,Y,,Kent,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,Braton,,,
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Y,N,Skywalker,910 Tatooine Road,Tatooine,

## 5.4 Using 'replace' to clean unwanted characters among others

In [101]:
#Leave only numbers for the column 'Phone_Number'

#df['Phone_Number'].str.replace ('[^a-zA-Z0-9]','')

# I runned it and it worked so now we can save it

#df['Phone_Number'] = df['Phone_Number'].str.replace ('[^a-zA-Z0-9]','')

In [76]:
# Dropped it cause its no longer I column to work on.

df= df.drop (columns ='Phone_Number')
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Yes,No,Baggins,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,93 West Main Street,No,Yes,Nadir,93 West Main Street,None,None
2,1003,Walter,White,298 Drugs Driveway,N,NaN,/White,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Schrute,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,123 Dragons Road,Y,No,Snow,123 Dragons Road,None,None
5,1006,Ron,Swanson,768 City Parkway,Yes,Yes,Swanson,768 City Parkway,None,None
6,1007,Jeff,Winger,1209 South Street,No,No,Winger,1209 South Street,None,None
7,1008,Sherlock,Holmes,98 Clue Drive,N,No,Holmes,98 Clue Drive,None,None
8,1009,Gandalf,NaN,123 Middle Earth,Yes,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,"25th Main Street, New York",Yes,No,Parker,25th Main Street,New York,None
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Yes,No,Gamgee,612 Shire Lane,Shire,None
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,NaN,Potter,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,2039 Main Street,Yes,N,Draper,2039 Main Street,None,None
13,1014,Leslie,Knope,343 City Parkway,Yes,No,Knope,343 City Parkway,None,None
14,1015,Toby,Flenderson,214 HR Avenue,N,No,Flenderson_,214 HR Avenue,None,None
15,1016,Ron,Weasley,2395 Hogwarts Avenue,No,N,Weasley,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Yes,No,Scott,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,3498 Super Lane,Y,NaN,Kent,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,Yes,Braton,N/a,None,None
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Yes,N,Skywalker,910 Tatooine Road,Tatooine,None

## 5.5 Splitting columns

The adress can be separated in 3 columns [Number_avenue_postcode] an they have comma

In [77]:
df[['Street_Address','Street','Zip_Code']]=df['Address'].str.split(',',2,expand = True)

/var/folders/vb/5jbwjmqj6j1b147zcdq7777h0000gn/T/ipykernel_6131/999537462.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['Street_Address','Street','Zip_Code']]=df['Address'].str.split(',',2,expand = True)

In [78]:
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Yes,No,Baggins,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,93 West Main Street,No,Yes,Nadir,93 West Main Street,None,None
2,1003,Walter,White,298 Drugs Driveway,N,NaN,/White,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Schrute,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,123 Dragons Road,Y,No,Snow,123 Dragons Road,None,None
5,1006,Ron,Swanson,768 City Parkway,Yes,Yes,Swanson,768 City Parkway,None,None
6,1007,Jeff,Winger,1209 South Street,No,No,Winger,1209 South Street,None,None
7,1008,Sherlock,Holmes,98 Clue Drive,N,No,Holmes,98 Clue Drive,None,None
8,1009,Gandalf,NaN,123 Middle Earth,Yes,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,"25th Main Street, New York",Yes,No,Parker,25th Main Street,New York,None
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Yes,No,Gamgee,612 Shire Lane,Shire,None
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,NaN,Potter,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,2039 Main Street,Yes,N,Draper,2039 Main Street,None,None
13,1014,Leslie,Knope,343 City Parkway,Yes,No,Knope,343 City Parkway,None,None
14,1015,Toby,Flenderson,214 HR Avenue,N,No,Flenderson_,214 HR Avenue,None,None
15,1016,Ron,Weasley,2395 Hogwarts Avenue,No,N,Weasley,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Yes,No,Scott,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,3498 Super Lane,Y,NaN,Kent,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,Yes,Braton,N/a,None,None
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Yes,N,Skywalker,910 Tatooine Road,Tatooine,None

## 5.6 Standarize [Yes/Y | No/N]

In [81]:
df['Paying Customer']= df['Paying Customer'].str.replace ('Yes','Y')
df['Paying Customer']= df['Paying Customer'].str.replace ('No','N')
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Y,No,Baggins,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,93 West Main Street,N,Yes,Nadir,93 West Main Street,None,None
2,1003,Walter,White,298 Drugs Driveway,N,NaN,/White,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,123 Dragons Road,Y,No,Snow,123 Dragons Road,None,None
5,1006,Ron,Swanson,768 City Parkway,Y,Yes,Swanson,768 City Parkway,None,None
6,1007,Jeff,Winger,1209 South Street,N,No,Winger,1209 South Street,None,None
7,1008,Sherlock,Holmes,98 Clue Drive,N,No,Holmes,98 Clue Drive,None,None
8,1009,Gandalf,NaN,123 Middle Earth,Y,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,"25th Main Street, New York",Y,No,Parker,25th Main Street,New York,None
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Y,No,Gamgee,612 Shire Lane,Shire,None
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,NaN,Potter,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,2039 Main Street,Y,N,Draper,2039 Main Street,None,None
13,1014,Leslie,Knope,343 City Parkway,Y,No,Knope,343 City Parkway,None,None
14,1015,Toby,Flenderson,214 HR Avenue,N,No,Flenderson_,214 HR Avenue,None,None
15,1016,Ron,Weasley,2395 Hogwarts Avenue,N,N,Weasley,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Y,No,Scott,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,3498 Super Lane,Y,NaN,Kent,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,Yes,Braton,N/a,None,None
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Y,N,Skywalker,910 Tatooine Road,Tatooine,None

In [83]:
df['Do_Not_Contact']= df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']= df['Do_Not_Contact'].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Y,N,Baggins,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,93 West Main Street,N,Y,Nadir,93 West Main Street,None,None
2,1003,Walter,White,298 Drugs Driveway,N,NaN,/White,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,123 Dragons Road,Y,N,Snow,123 Dragons Road,None,None
5,1006,Ron,Swanson,768 City Parkway,Y,Y,Swanson,768 City Parkway,None,None
6,1007,Jeff,Winger,1209 South Street,N,N,Winger,1209 South Street,None,None
7,1008,Sherlock,Holmes,98 Clue Drive,N,N,Holmes,98 Clue Drive,None,None
8,1009,Gandalf,NaN,123 Middle Earth,Y,NaN,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,"25th Main Street, New York",Y,N,Parker,25th Main Street,New York,None
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Y,N,Gamgee,612 Shire Lane,Shire,None
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,NaN,Potter,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,2039 Main Street,Y,N,Draper,2039 Main Street,None,None
13,1014,Leslie,Knope,343 City Parkway,Y,N,Knope,343 City Parkway,None,None
14,1015,Toby,Flenderson,214 HR Avenue,N,N,Flenderson_,214 HR Avenue,None,None
15,1016,Ron,Weasley,2395 Hogwarts Avenue,N,N,Weasley,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Y,N,Scott,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,3498 Super Lane,Y,NaN,Kent,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,Y,Braton,N/a,None,None
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Y,N,Skywalker,910 Tatooine Road,Tatooine,None

In [95]:
df.isnull().sum()

CustomerID         0
First_Name         0
Last_Name          0
Address            0
Paying Customer    0
Do_Not_Contact     0
Last_name          0
Street_Address     0
Street             0
Zip_Code           0
dtype: int64

## 5.7 Replace for the ENTIRE dataframe (df)

In [87]:
df = df.replace('N/a','')

In [89]:
# NaN is not a value , technically is empty

# fillna fill every space with a blank | I used the 'inplace' to remember the use

df.fillna('',inplace = True)

In [100]:
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Y,N,Baggins,123 Shire Lane,Shire,
1,1002,Abed,Nadir,93 West Main Street,N,Y,Nadir,93 West Main Street,,
2,1003,Walter,White,298 Drugs Driveway,N,,/White,298 Drugs Driveway,,
3,1004,Dwight,Schrute,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Schrute,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,123 Dragons Road,Y,N,Snow,123 Dragons Road,,
5,1006,Ron,Swanson,768 City Parkway,Y,Y,Swanson,768 City Parkway,,
6,1007,Jeff,Winger,1209 South Street,N,N,Winger,1209 South Street,,
7,1008,Sherlock,Holmes,98 Clue Drive,N,N,Holmes,98 Clue Drive,,
8,1009,Gandalf,,123 Middle Earth,Y,,,123 Middle Earth,,
9,1010,Peter,Parker,"25th Main Street, New York",Y,N,Parker,25th Main Street,New York,
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Y,N,Gamgee,612 Shire Lane,Shire,
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,,Potter,2394 Hogwarts Avenue,,
12,1013,Don,Draper,2039 Main Street,Y,N,Draper,2039 Main Street,,
13,1014,Leslie,Knope,343 City Parkway,Y,N,Knope,343 City Parkway,,
14,1015,Toby,Flenderson,214 HR Avenue,N,N,Flenderson_,214 HR Avenue,,
15,1016,Ron,Weasley,2395 Hogwarts Avenue,N,N,Weasley,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Y,N,Scott,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,3498 Super Lane,Y,,Kent,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,Braton,,,
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Y,N,Skywalker,910 Tatooine Road,Tatooine,

In [110]:
# Cleaning characters around the 'last names'

df['Last_name']= df['Last_name'].str.lstrip('/')
df['Last_name']= df['Last_name'].str.rstrip('_')
df

,CustomerID,First_Name,Last_Name,Address,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,"123 Shire Lane, Shire",Y,N,Baggins,123 Shire Lane,Shire,
2,1003,Walter,White,298 Drugs Driveway,N,,White,298 Drugs Driveway,,
4,1005,Jon,Snow,123 Dragons Road,Y,N,Snow,123 Dragons Road,,
6,1007,Jeff,Winger,1209 South Street,N,N,Winger,1209 South Street,,
7,1008,Sherlock,Holmes,98 Clue Drive,N,N,Holmes,98 Clue Drive,,
8,1009,Gandalf,,123 Middle Earth,Y,,,123 Middle Earth,,
9,1010,Peter,Parker,"25th Main Street, New York",Y,N,Parker,25th Main Street,New York,
10,1011,Samwise,Gamgee,"612 Shire Lane, Shire",Y,N,Gamgee,612 Shire Lane,Shire,
11,1012,Harry,Potter,2394 Hogwarts Avenue,Y,,Potter,2394 Hogwarts Avenue,,
12,1013,Don,Draper,2039 Main Street,Y,N,Draper,2039 Main Street,,
13,1014,Leslie,Knope,343 City Parkway,Y,N,Knope,343 City Parkway,,
14,1015,Toby,Flenderson,214 HR Avenue,N,N,Flenderson,214 HR Avenue,,
15,1016,Ron,Weasley,2395 Hogwarts Avenue,N,N,Weasley,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,"121 Paper Avenue, Pennsylvania",Y,N,Scott,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,3498 Super Lane,Y,,Kent,3498 Super Lane,,
19,1020,Anakin,Skywalker,"910 Tatooine Road, Tatooine",Y,N,Skywalker,910 Tatooine Road,Tatooine,

In [111]:
# Dropping the adress cause we alreay have new 3 columns

df.drop (columns = 'Address',inplace = True)

## 5.8 Leave only numbers allow to call by 'Y'

In [116]:
for x in df.index:
    if df.loc[x,'Do_Not_Contact'] == 'Y':
        df.drop (x,inplace=True)
    
df

#This would be the list of contacts to call, 
#they either directly responden NO when asked 'not called' or did not respond.

,CustomerID,First_Name,Last_Name,Paying Customer,Do_Not_Contact,Last_name,Street_Address,Street,Zip_Code
0,1001,Frodo,Baggins,Y,N,Baggins,123 Shire Lane,Shire,
2,1003,Walter,White,N,,White,298 Drugs Driveway,,
4,1005,Jon,Snow,Y,N,Snow,123 Dragons Road,,
6,1007,Jeff,Winger,N,N,Winger,1209 South Street,,
7,1008,Sherlock,Holmes,N,N,Holmes,98 Clue Drive,,
8,1009,Gandalf,,Y,,,123 Middle Earth,,
9,1010,Peter,Parker,Y,N,Parker,25th Main Street,New York,
10,1011,Samwise,Gamgee,Y,N,Gamgee,612 Shire Lane,Shire,
11,1012,Harry,Potter,Y,,Potter,2394 Hogwarts Avenue,,
12,1013,Don,Draper,Y,N,Draper,2039 Main Street,,
13,1014,Leslie,Knope,Y,N,Knope,343 City Parkway,,
14,1015,Toby,Flenderson,N,N,Flenderson,214 HR Avenue,,
15,1016,Ron,Weasley,N,N,Weasley,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,Y,N,Scott,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,Y,,Kent,3498 Super Lane,,
19,1020,Anakin,Skywalker,Y,N,Skywalker,910 Tatooine Road,Tatooine,